### ISSUE TITLE
Possibly missing some ports

### ISSUE THREAD

**Issue by bedalus** [Azure-Samples/azure-data-factory-runtime-app-service#1]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Follow the instructions, successfully deploy an IR against an active factory and wait a few days.

### Any log messages given by the failure
Node vanished from factory IR. The app service deployment center logs show the container was restarted as a 'background worker' with something about ports. Sorry can't remember exact message. It did not reconnect with the factory.

### Expected/desired behavior
No failure, or if restarts, correctly reconnects to the factory.

### OS and Version?
Windows, as per the deployment

### Versions
Using the latest SHIR (downloaded IntegrationRuntime_5.23.8324.1.msi) 

### Mention any other details that might be useful
It was half guess-work, but I added the following ports after the RUN line in Dockerfile:
```
RUN ["powershell", "C:/SHIR/build.ps1"]

ENV PORT=1433
EXPOSE $PORT

ENV PORT=8060
EXPOSE $PORT

ENV WEBSITES_PORT=443
EXPOSE $WEBSITES_PORT
```

It may be pure luck, but the IR has not failed in 12 days. I think before this the longest we saw was 4 days, the median maybe 3.

Is it possible to say why this might have helped? Or should I revert, and retry and see if coincidence? Or wait longer to observe current behavior? I actually hoping it would fail as usual to see the if the added ports would have made any effect.

Was also wondering, can I use this method to add multiple nodes? I tried scaling out, but this didn't seem to have any impact (no change to the registered nodes in ADF)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bedalus** [comment]
Ah, I need to clarify that I'm building the container locally and pushing to an existing container registry in azure, so my deployment differs a little. But the rest is the same (using the bicep to deploy the app)

**Comment by johndowns** [comment]
Hi @bedalus, as I understand it, you shouldn't need to expose any incoming ports for the self-hosted integration runtime to work. The scenarios in which the SHIR is used are such that incoming ports usually are blocked anyway.

In any case, it sounds like your issue is unrelated to this sample (which is about how to run the container image on App Service) and is instead about the configuration of the container image. I'd suggest you do the following:
- Open an Azure support case, and ask the support engineer to help you to identify why your node vanished from the factory.
- If you think there needs to be a configuration change made to the container image, please open an issue or pull request against the [SHIR container image repo](https://github.com/Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container/).

**Comment by bedalus** [comment]
I agree, after rebuilding the container without those ports, it's been running just fine for over a week now. I'll open a support case if I see the same again. Thanks

**Comment by bedalus** [comment]
So it has failed again without these ports open, and has generated a log (found under the deployment center logs within the app):

```
2022_12_12_xn0sdwk000042_platform.log:
12/12/2022 09:19:49.739 ERROR - Site: udal-core-app-adf-ir-prod - [381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98] - Container entrypoint is no longer running.
12/12/2022 09:20:03.399 INFO - Site: udal-core-app-adf-ir-prod - [381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98] - Attempting to stop container: 381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98. Site udal-core-app-adf-ir-prod
12/12/2022 09:20:11.585 INFO - Site: udal-core-app-adf-ir-prod - [381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98] - Shutdown container: 381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98
12/12/2022 09:20:11.601 INFO - Site: udal-core-app-adf-ir-prod - [381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98] - Attempting to remove container: 381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98
12/12/2022 09:20:12.495 INFO - Site: udal-core-app-adf-ir-prod - [381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98] - Container removed successfully. Container Id: 381e95f87055e417364aac8edce73da32f0b873fd35af7c04f931357f52e8d98
12/12/2022 09:20:12.495 INFO - Site: udal-core-app-adf-ir-prod - Purging pending logs after stopping container
12/12/2022 09:20:15.804 INFO - Site: udal-core-app-adf-ir-prod - Creating container image
12/12/2022 09:20:15.976 INFO - Site: udal-core-app-adf-ir-prod - Verifying container image and pull image if necesary
12/12/2022 09:20:17.492 INFO - Site: udal-core-app-adf-ir-prod - Pulling container image: udalcrcoreprod.azurecr.io/udal-core-adf-ir-prod:latest. AuthType: Token
12/12/2022 09:20:18.449 INFO - Site: udal-core-app-adf-ir-prod - Image: udalcrcoreprod.azurecr.io/udal-core-adf-ir-prod:latest
Status: latest Pulling from udal-core-adf-ir-prod

12/12/2022 09:20:18.494 INFO - Site: udal-core-app-adf-ir-prod - Image: udalcrcoreprod.azurecr.io/udal-core-adf-ir-prod:latest
Status: Digest: sha256:feb3c87a16910f17a0689fa1756f61ff191c37f753e946bb75512b2e140ea196

12/12/2022 09:20:18.494 INFO - Site: udal-core-app-adf-ir-prod - Image: udalcrcoreprod.azurecr.io/udal-core-adf-ir-prod:latest
Status: Status: Image is up to date for udalcrcoreprod.azurecr.io/udal-core-adf-ir-prod:latest

12/12/2022 09:20:18.842 INFO - Site: udal-core-app-adf-ir-prod - Attempting to create container
12/12/2022 09:20:18.842 INFO - Site: udal-core-app-adf-ir-prod - Creating container for image: udalcrcoreprod.azurecr.io/udal-core-adf-ir-prod:latest.
12/12/2022 09:20:19.544 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Create container for image: udalcrcoreprod.azurecr.io/udal-core-adf-ir-prod:latest succeeded. Container Id 32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd
12/12/2022 09:20:19.544 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Attempting to start container. Container memory limit: 1024 MB. For more information, refer https://aka.ms/configurecontainer.
12/12/2022 09:20:50.776 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Start container succeeded.
12/12/2022 09:21:01.633 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Container has started.
12/12/2022 09:21:01.633 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Customizing the container
12/12/2022 09:21:04.446 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Container customization has completed successfully
12/12/2022 09:21:04.477 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Container has started.
12/12/2022 09:21:06.531 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Container entrypoint has started
12/12/2022 09:21:06.531 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - The container doesn't have a port exposed and it will continue running as a background worker.
12/12/2022 09:21:06.546 INFO - Site: udal-core-app-adf-ir-prod - [32a574603920f67a77ab8c3953433a1efeeeefeb5929c1b8082d8451c4eca0fd] - Container start-up and configuration completed successfully
```

The message "The container doesn't have a port exposed and it will continue running as a background worker" is identical to what we saw initially when I first raised this issue, and caused us to rebuild with the ports.

The automatic repair (or whatever restarts the container) does not result in a re-attach to the ADF IR. The only way that I have found to do fix is to delete the node from ADF IR, and delete the app from Azure, then redeploy it.

As it currently is, I cannot rely on this for a production process. Can you see anything here that I might have missed?

**Comment by jikuja** [comment]
Other work(1) is using undocumented command-line arguments:
* setup timeout: https://github.com/ingenii-solutions/azure-data-factory-self-hosted-runtime/blob/main/scripts/entrypoint.ps1#L61-L66
* and use timeout: https://github.com/ingenii-solutions/azure-data-factory-self-hosted-runtime/blob/main/scripts/entrypoint.ps1#L74

I have not tested that code or even parameter usage because ACI does not support VNets with windows. If that's a real parameter for `dmgcmd.exe -RegisterNewNode` it looks like a good solution. Sadly API for SHIR registeration is not documented.

(1) https://github.com/ingenii-solutions/azure-data-factory-self-hosted-runtime

------

About the issue: do you have a log from data factory? At least critital, error and warning events?

I feel like ACI could be e.g. running out of memory and then instance is killed. The `The container doesn't have a port exposed and it will continue running as a background worker.` is probably printed for all containers not exposing ports. 

SHIR itself does not handle incoming TCP connections except port for high-availability if HA is enabled. The main point of gateway component is to reverse traffic flow in order not to have requirements for incoming traffic.

**Comment by bedalus** [comment]
I've just now performed this sequence of steps:

1. Delete the node (named 'AppServiceContainer') from the ADF IR
2. Restart the app

This has solved half the problem. With the 'AppServiceContainer' removed from ADF, it seems the restarted app is able to register with the IR again with the same name. 

When the app restarts itself, action (1) does not happen.

Would it be possible for the name to be incremented each time to observe if the container restarts itself, that it is able to automatically re-register as a node with a distinct name?

**Comment by jikuja** [comment]
Or you could try deleting node before starting SHIR: https://learn.microsoft.com/en-us/rest/api/datafactory/integration-runtime-nodes/delete?tabs=HTTP

IIRC integration runtime can have only four nodes.

**Comment by johndowns** [comment]
@bedalus As per my earlier comment, I think the best way forward would be to open a support case.

However note that *the lack of incoming ports is intentional*. The SHIR is designed to work with a relay service, which means it doesn't have incoming ports opened. So I doubt that the issue you're seeing relates in any way to ports.

**Comment by bedalus** [comment]
Thanks John. I already agree, just wanted to provide the logs that were missing in the original post to explain my line of reasoning at the time. It was certainly a red herring :) 

I'm just now redeploying with a tweak to the entrypoint (setup.ps1) that calls the RegisterNewNode function with a unique node name generated using a partial date/time combined with a short GUID.

If I'm right, this should allow me to register multiple nodes by scaling out (as each new instance will register with a distinct name), and also fix the problem with failures, as when an instance restarts by itself, it also gets a distinct name.

The edited section (line 95 of setup.ps1):

```
$nodeName = (get-date -Format yyyyMMdd-HHmm)+"-IRnode-"+([guid]::NewGuid() -split '-')[0]
# Was previously $Env:NODE_NAME
RegisterNewNode $Env:AUTH_KEY $nodeName $Env:ENABLE_HA $Env:HA_PORT
```
